conda-forge/root-feedstock

- .azure-pipelines/build_steps.sh
- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- recipe/FindX11.cmake
- recipe/build.sh
- recipe/cross-linux.cmake
- recipe/meta.yaml
- recipe/toolchain.cmake
- recipe/yum_requirements.txt
Checklist
Changes:
* Fixes #25 by adding `-Dopengl=ON`
* Uses Anaconda Inc's [CMake recommendations](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html?highlight=cmake#an-aside-on-cmake-and-sysroots)
* Add support for `ROOT_JENKINS_GIT_URL`, `ROOT_JENKINS_GIT_URL` and `ROOT_RUN_GTESTS` environment variables so ROOT's nightlies can use this recipe directly
* Use GNU `sed` from conda-forge for patching the sources instead of relying on the host
* Copy the [upstream `FindX11.cmake`](https://github.com/Kitware/CMake/blob/e59e17c1c7059b7d0f02d6b12bc3094a2afee778/Modules/FindX11.cmake) file and add minor patches as I couldn't figure out how to configure CMake correctly
> Fix opengl

- recipe/meta.yaml
> Downgrade davix and add a test

- recipe/build.sh
- recipe/meta.yaml
> Include _rdict.pcm files

- recipe/meta.yaml
> Fix root_base runtime dependencies

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/linux_python3.8.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- .ci_support/osx_python3.8.yaml
- recipe/meta.yaml
> Remove version constraints to fix pinning mechanism

- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- recipe/meta.yaml
> Fix macOS build

- recipe/build_root-base.sh
- recipe/meta.yaml
Deals with the issue reported in: https://github.com/scikit-hep/uproot/pull/463
Checklist
> Fix RDF::ToNumpy

- README.md
- recipe/meta.yaml
> Update to 6.20.4

- .ci_support/linux_python3.6.____cpython.yaml
- .ci_support/linux_python3.7.____cpython.yaml
- .ci_support/linux_python3.8.____cpython.yaml
- .ci_support/migrations/glew210.yaml
- .ci_support/migrations/lz4_c192.yaml
- .ci_support/osx_python3.6.____cpython.yaml
- .ci_support/osx_python3.7.____cpython.yaml
- .ci_support/osx_python3.8.____cpython.yaml
- .scripts/build_steps.sh
- recipe/build_root-base.sh
- recipe/meta.yaml
> WIP: Pin zstd

- recipe/meta.yaml
- recipe/patches/root-6.20.0-install-pyroot-headers.patch
@conda-forge-admin, please rerender
Checklist
> [Python 2 backport] Install additional PyROOT headers

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/migrations/xrootd412.yaml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
- recipe/patches/root-6.20.0-install-pyroot-headers.patch
@conda-forge-admin, please rerender
Checklist
> Install additional PyROOT headers

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- LICENSE.txt
- README.md
- recipe/build_root-base.sh
- recipe/meta.yaml
> Depend on sysroot and add configuration for nightly builds in jenkins

- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- recipe/build_root-base.sh
- recipe/jupyter_notebook_config.py
- recipe/meta.yaml
- recipe/patches/jupyroot.patch
- recipe/test_pyroot.py
> Fix jupyter

- .scripts/run_osx_build.sh
- recipe/build_root-base.sh
- recipe/meta.yaml
Checklist
@conda-forge-admin, please rerender
> Update to 6.22.2

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/migrations/lz4-c193.yaml
- .ci_support/osx_64_numpy1.16python3.6.____cpython.yaml
- .ci_support/osx_64_numpy1.16python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.16python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .scripts/run_docker_build.sh
> Rebuild for lz4-c193

- recipe/meta.yaml
> Update to 6.22.8

- .ci_support/linux_64_numpy1.17python3.6.____cpython.yaml
- .ci_support/linux_64_numpy1.17python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.17python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.17python3.6.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.17python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.17python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.17python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.17python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.17python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.17python3.6.____cpython.yaml
- .ci_support/osx_64_numpy1.17python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.17python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- recipe/build.sh
- recipe/meta.yaml
> Stop targetting nehalem

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/migrations/zstd15.yaml
- recipe/meta.yaml
> Update to v6.24.2

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_numpy1.18python3.6.____cpython.yaml
- .ci_support/linux_64_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.6.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/migrations/gsl27.yaml
- .ci_support/migrations/tbb2021.yaml
- .ci_support/osx_64_numpy1.18python3.6.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .drone.yml
- .travis.yml
- README.md
- recipe/meta.yaml
- recipe/patches/0001-Workaround-https-github.com-root-project-root-issues.patch
- recipe/test_pyroot.py
This PR is a manual migration to gsl2.7, for some reason this feedstock is listed as 'not solvable' on the [migration status](https://conda-forge.org/status/#gsl27) with the following error
```
Encountered problems while solving:
- nothing provides requested libllvm9 9.0.1.* 2
```
which I don't understand.
Checklist
> Rebuild for gsl27

- recipe/meta.yaml
> Update to 6.24.6

- recipe/meta.yaml
Checklist
Hopefully fixes #158
> Fix pinning on nlohmann_json

- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
Needed for https://github.com/conda-forge/yoda-feedstock/pull/17
Checklist
> Fix osx target for arm64

- .ci_support/linux_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/migrations/lz4_c19.yaml
- .ci_support/osx_64_numpy1.19python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .circleci/config.yml
- recipe/meta.yaml
> Update to 6.26.4

- .ci_support/linux_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.23python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.20python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.23python3.11.____cpython.yaml
- .ci_support/migrations/cfitsio420.yaml
- .ci_support/osx_64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- conda-forge.yml
- recipe/meta.yaml
This is a rebased version of #193.
Checklist
> Rebuild for cfitsio420

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.8.____cpython.yaml
- .ci_support/linux_64_numpy1.21python3.9.____cpython.yaml
- .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.23python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.23python3.11.____cpython.yaml
- .ci_support/migrations/graphviz8.yaml
- .ci_support/migrations/libtiff45.yaml
- .ci_support/migrations/libxml2211.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .travis.yml
- README.md
- recipe/meta.yaml
Closes #206
Closes #200
Closes #201
> Apply migrations

- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/recipe.yaml
> Update to v6.32.10

- recipe/recipe.yaml
> Update for 6.34.10

- recipe/build_root.sh
- recipe/deactivate.csh
- recipe/get_cpu_arch.sh
- recipe/recipe.yaml
Checklist
Fixes https://github.com/conda-forge/root-feedstock/issues/278
> Export CONDA_BUILD_SYSROOT in non-bourne-like shells
